name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Frontend Image
      run: docker build -t ${{ secrets.REGISTRY_URL }}/frontend ./frontend

    - name: Build Backend Image
      run: docker build -t ${{ secrets.REGISTRY_URL }}/backend ./backend

    - name: Push Frontend Image
      run: docker push ${{ secrets.REGISTRY_URL }}/frontend

    - name: Push Backend Image
      run: docker push ${{ secrets.REGISTRY_URL }}/backend

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f config/kubernetes/frontend-deployment.yaml
        kubectl apply -f config/kubernetes/backend-deployment.yaml
        kubectl apply -f config/kubernetes/ingress.yaml
